Repository Team-useMemo/Jugger-Frontend-Web, pull requests merged in 2025-06, with the labels that each got.

#96 #54 [Fix] 메모 조회 로직 수정
  src/pages/Memo/page.tsx
  src/stores/modules/memo.ts
Labels: 🐞 BugFix

#100 #54 [Feat] 검색 API 연결
  src/components/Modal/Search/Search.tsx
Labels: 📬 API, ✨ Feature

#103 #11 [Feat] 사이드바 모바일 반응형 구현
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/layout/Header/Header.tsx
  src/layout/MainLayout/MainLayout.tsx
  src/layout/SideBar/SideBar.tsx
Labels: ✨ Feature

#104 Feat/#54 api connect
  src/components/Memo/Text/MemoText.tsx
  src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx
  src/components/Modal/MemoCollection/MemoCollection.tsx
  src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.tsx
  src/layout/Header/Header.tsx
  src/layout/SideBar/SideBar.tsx
  src/pages/Login/LoginPage.style.ts
  src/pages/Login/page.tsx
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
  src/stores/modules/memo.ts
Labels: 📬 API, ✨ Feature

#108 #54 [Feat] 메모 수정
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
Labels: ✨ Feature

#111 Feat/#110 responsive UI
  src/assets/icons/category.svg
  src/assets/icons/plus.svg
  src/components/ContextMenu/ContextMenu.Style.ts
  src/components/Memo/Link/MemoLink.Style.ts
  src/components/Memo/Link/MemoLink.tsx
  src/components/Memo/Memo.Style.ts
  src/components/Memo/Memo.tsx
  src/components/Memo/Schedule/MemoSchedule.Style.ts
  src/components/Memo/Text/MemoText.Style.ts
  src/components/Modal/Background/FullGrayLeftComponent.tsx
  src/components/Modal/Category/AddCategory.tsx
  src/components/Modal/Category/EditCategory.tsx
  src/components/Modal/Layout/ModalLayoutGray.tsx
  src/components/Modal/Layout/ModalLayoutGrayLeft.tsx
  src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx
  src/components/Modal/MemoCollection/MemoCollection.Style.ts
  src/components/Modal/MemoCollection/MemoCollection.tsx
  src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.tsx
  src/components/Modal/MemoViewer/Image/AddImageMemo.tsx
  src/components/Modal/MemoViewer/Schedule/AddScheduleMemo.tsx
  src/components/Modal/SearchMemo/SearchMemo.tsx
  src/components/SideBar/SideMenu/SideMenu.Style.ts
  src/components/SideBar/SideMenu/SideMenu.tsx
  src/components/SideBar/SideMessage/SideMessage.Style.ts
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/mock/category.ts
  src/hooks/useContextMenu.tsx
  src/hooks/useParamModal.tsx
  src/hooks/useStateRef.ts
  src/hooks/useWindowSize.tsx
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  src/layout/MainLayout/MainLayout.Style.ts
  src/layout/MainLayout/MainLayout.tsx
  src/layout/SideBar/SideBar.style.ts
  src/layout/SideBar/SideBar.tsx
  src/pages/Login/LoginPage.style.ts
  src/pages/Login/page.tsx
  src/pages/Memo/MemoPage.Style.ts
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
  src/stores/modules/modal.ts
  src/ts/Category.Prop.ts
  src/utils/Modal.ts
  src/utils/Search.ts
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🔨 Refactor, 🎨 Styling

#115 #114 [feat] 임시 로그아웃 버튼 구현
  src/controllers/api.Type.ts
  src/layout/Header/Header.tsx
  src/layout/SideBar/SideBar.style.ts
  src/layout/SideBar/SideBar.tsx
  src/utils/Auth.ts
Labels: 💻 CrossBrowsing, ✨ Feature

#117 #69 [Feat] 구글 로그인 추가
  .env
  .env.production
  src/components/Popup/Auth/Info/Info.tsx
  src/controllers/api.ts
  src/pages/Login/page.tsx
  src/pages/Oauth/Callback.tsx
  src/router/index.tsx
Labels: 📬 API, ✨ Feature

#119 #54 [Feat] 일정 추가 로직 수정
  src/components/Modal/MemoDetail/Schedule/MemoDetailSchedule.tsx
  src/components/Modal/MemoEditor/Schedule/MemoEditorSchedule.tsx
  src/controllers/api.ts
  src/controllers/mock/memo.ts
  src/stores/modules/memo.ts
Labels: 📬 API

#121 #54 [Feat] 일정 관련 수정 사항 반영
  src/components/Memo/Schedule/MemoSchedule.tsx
  src/components/Modal/MemoEditor/Schedule/MemoEditorSchedule.tsx
  src/stores/modules/memo.ts
Labels: ✨ Feature

#124 #54 [Feat] 메모 카테고리 변경 기능 구현 중
  src/components/Memo/Memo.tsx
  src/components/Modal/EditMemoCategory/EditMemoCategory.tsx
Labels: ✨ Feature

#128 #54 [Feat] API 수정사항 연동
  .env
  src/components/Memo/Image/MemoImage.tsx
  src/components/Memo/Memo.tsx
  src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx
  src/components/Modal/MemoDetail/Image/MemoDetailImage.Style.ts
  src/components/Modal/MemoDetail/Image/MemoDetailImage.tsx
  src/pages/Login/page.tsx
  src/stores/modules/memo.ts
  src/ts/Memo.Prop.ts
Labels: 📬 API
