Repository Team-useMemo/Jugger-Frontend-Web, pull requests merged in 2025-04, with the labels that each got.

#24 #22 자세히 보기 구현
  src/assets/icons/category.svg
  src/assets/icons/download.svg
  src/assets/icons/expand.svg
  src/assets/icons/right_arrow.svg
  src/components/Memo/Image/MemoImage.tsx
  src/components/Memo/Memo.tsx
  src/components/Memo/Schedule/MemoSchedule.tsx
  src/components/Memo/Text/MemoText.tsx
  src/components/Modal/AddImageModal.tsx
  src/components/Modal/Modal.Style.ts
  src/components/Modal/ScheduleModal.tsx
  src/pages/Memo/page.tsx
Labels: ✨ Feature

#26 #25 카테고리 추가 기능 구현
  src/components/Modal/AddCategory.tsx
  src/layout/SideBar/SideBar.tsx
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
  src/stores/modules/memo.ts
Labels: ✨ Feature

#31 #30 디자인 시스템 적용
  src/components/Memo/Text/MemoText.tsx
  src/pages/Login/page.tsx
  src/styles/theme.ts
Labels: 🎨 Styling

#32 #27 메모 모아보기 구현
  src/assets/icons/left_arrow.svg
  src/assets/icons/loading.svg
  src/assets/icons/right_arrow.svg
  src/components/Memo/Image/MemoImage.tsx
  src/components/Memo/Text/MemoText.tsx
  src/components/Modal/AboutImage.tsx
  src/components/Modal/GatherContents.tsx
  src/layout/SideBar/SideBar.tsx
  src/stores/modules/category.ts
Labels: ✨ Feature

#34 #11 [feat] 우클릭이벤트 생성
  src/components/SideBar/SideMessage/SideMessage.Style.ts
  src/components/SideBar/SideMessage/SideMessage.tsx
Labels: ✨ Feature

#35 [feat] 드래그 기능 구현
  src/assets/Sidebar/SettingPin.svg
  src/components/SideBar/SideMessage/ContextMenu/ContextMenu.Style.ts
  src/components/SideBar/SideMessage/ContextMenu/ContextMenu.tsx
  src/components/SideBar/SideMessage/SideMessage.Style.ts
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/layout/SideBar/SideBar.style.ts
  src/layout/SideBar/SideBar.tsx
Labels: ✨ Feature

#36 #11 [feat] 카테고리 변경 구현
  src/components/Modal/EditCategory.tsx
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/stores/modules/category.ts
Labels: ✨ Feature

#39 #11 [fix] 모바일 롱클릭 기본 이벤트 블락
  src/components/SideBar/SideMessage/SideMessage.Style.ts
Labels: 🐞 BugFix

#41 #11 [feat] 카테고리 추가/설정 모달 반응형 구현
  src/components/Modal/AddCategory.tsx
  src/components/Modal/EditCategory.tsx
  src/components/Modal/Modal.Style.ts
Labels: 💻 CrossBrowsing, 🎨 Styling

#46 #44 [fix] 사이드바메뉴 겹치는 이슈 fix
  src/components/Modal/GatherContents.tsx
Labels: 🐞 BugFix

#47 메모 관련 리팩토링
  src/assets/icons/right_arrow.svg
  src/assets/icons/time_circle.svg
  src/components/Memo/Image/MemoImage.Style.ts
  src/components/Memo/Image/MemoImage.tsx
  src/components/Memo/Link/MemoLink.Style.ts
  src/components/Memo/Link/MemoLink.tsx
  src/components/Memo/Memo.Style.ts
  src/components/Memo/Memo.tsx
  src/components/Memo/Schedule/MemoSchedule.Style.ts
  src/components/Memo/Schedule/MemoSchedule.tsx
  src/components/Memo/Text/MemoText.Style.ts
  src/components/Memo/Text/MemoText.tsx
  src/components/Modal/AboutImage.tsx
  src/components/Modal/AddCategory.tsx
  src/components/Modal/Background/BottomTransparent.tsx
  src/components/Modal/Background/FullScreenGray.tsx
  src/components/Modal/EditCategory.tsx
  src/components/Modal/GatherContents.tsx
  src/components/Modal/MemoViewer/Image/MemoAddImage.tsx
  src/components/Modal/MemoViewer/Image/MemoDetailImage.tsx
  src/components/Modal/MemoViewer/Image/MemoViewerImage.Style.tsx
  src/components/Modal/MemoViewer/MemoDetail/MemoDetailText.Style.ts
  src/components/Modal/MemoViewer/MemoDetail/MemoDetailText.tsx
  src/components/Modal/MemoViewer/MemoViewer.Style.ts
  src/components/Modal/MemoViewer/Schedule/MemoAddSchedule.tsx
  src/components/Modal/MemoViewer/Schedule/MemoDetailSchedule.tsx
  src/components/Modal/MemoViewer/Schedule/MemoViewerSchedule.Style.ts
  src/components/Modal/ScheduleModal.tsx
  src/components/Modal/SelectCalendar/SelectCalendar.Style.ts
  src/components/Modal/SelectCalendar/SelectCalendar.tsx
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/api.ts
  src/controllers/mock/category.ts
  src/controllers/mock/memo.ts
  src/hooks/useModal.tsx
  src/layout/MainLayout/MainLayout.tsx
  src/layout/SideBar/SideBar.tsx
  src/pages/Memo/MemoPage.Style.ts
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
  src/stores/modules/memo.ts
  src/ts/Category.Prop.ts
  src/ts/Memo.Prop.ts
  src/ts/type.ts
  src/utils/Date.ts
  src/utils/isUrl.ts
Labels: 🔨 Refactor

#48 #11 [feat] 핀아이콘 수정
  src/components/SideBar/SideMessage/SideMessage.Style.ts
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/components/SideBar/SideMessage/controllers/api.ts
  src/components/SideBar/SideMessage/controllers/mock/category.ts
  src/components/SideBar/SideMessage/controllers/mock/memo.ts
  src/layout/SideBar/SideBar.style.ts
Labels: ✨ Feature, 🎨 Styling

#49 #29 [feat] 검색 컴포넌트 UI 구현
  src/components/Modal/Modal.Style.ts
  src/components/Modal/SearchCategory.tsx
  src/layout/Header/Header.tsx
  src/layout/MainLayout/MainLayout.tsx
Labels: ✨ Feature

#50 #29 [feat] 검색 컴포넌트 구현
  src/assets/Search/Link.svg
  src/assets/Search/Photo.svg
  src/assets/Search/Schedule.svg
  src/assets/Search/Text.svg
  src/components/Modal/SearchCategory.tsx
Labels: ✨ Feature

#51 #29 [feat] 검색 컴포넌트 카테고리 로직 변경
  src/components/Modal/SearchCategory.tsx
Labels: ✨ Feature

#52 #29 [feat] 검색 컴포넌트 카테고리 로직 변경
  src/components/Modal/Search/Search.Style.ts
  src/components/Modal/Search/Search.tsx
  src/layout/Header/Header.tsx
Labels: 🔨 Refactor

#53 #29 [feat] 검색 결과 클릭시 해당 카테고리로 이동
  src/components/Modal/Search/Search.tsx
  src/layout/Header/Header.tsx
Labels: ✨ Feature

#55 #54 [feat] 메인 컴포넌트 API 연결 임시 구현
  .env
  src/controllers/api.ts
  src/controllers/mock/category.ts
  src/pages/Memo/page.tsx
  src/stores/modules/memo.ts
  vite.config.ts
Labels: 📬 API

#57 Feat/#54-API-connect
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/api.ts
  src/layout/SideBar/SideBar.tsx
  src/stores/modules/category.ts
Labels: 📬 API

#58 Feat/#19 memo modularize
  src/components/Memo/Image/MemoImage.tsx
  src/components/Memo/Link/MemoLink.tsx
  src/components/Memo/Memo.tsx
  src/components/Memo/Schedule/MemoSchedule.tsx
  src/components/Memo/Text/MemoText.tsx
  src/components/Modal/AddCategory.tsx
  src/components/Modal/GatherContents.tsx
  src/components/Modal/MemoCollection/Image/MemoCollectionImage.Style.ts
  src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.Style.ts
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx
  src/components/Modal/MemoCollection/MemoCollection.Style.ts
  src/components/Modal/MemoCollection/MemoCollection.tsx
  src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.Style.tsx
  src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.tsx
  src/components/Modal/MemoViewer/Image/MemoViewerImage.Style.tsx
  src/components/Modal/MemoViewer/MemoViewer.Style.ts
  src/components/Modal/MemoViewer/Schedule/MemoAddSchedule.tsx
  src/components/Modal/MemoViewer/Schedule/MemoDetailSchedule.tsx
  src/components/Modal/Modal.Style.ts
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/api.ts
  src/hooks/useModal.tsx
  src/layout/Header/Header.tsx
  src/layout/SideBar/SideBar.tsx
  src/pages/Memo/page.tsx
  src/utils/ogData.ts
Labels: 💻 CrossBrowsing, ✨ Feature, 🔨 Refactor

#59 #9 [feat] API 임시 연결
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/api.ts
  src/layout/SideBar/SideBar.tsx
  src/pages/Memo/page.tsx
  src/stores/modules/category.ts
  vite.config.ts
Labels: 📬 API

#60 #9 [feat] 카테고리별 메모 표시
  src/controllers/api.ts
  src/layout/SideBar/SideBar.tsx
  src/pages/Memo/page.tsx
Labels: ✨ Feature

#61 #9 [feat] 이미지 메모 POST API 연결
  src/components/Modal/Search/Search.tsx
  src/controllers/api.ts
  src/pages/Memo/page.tsx
Labels: 📬 API

#62 # 11 [feat] 모바일 롱클릭 이벤트 수정
  src/components/SideBar/SideMessage/SideMessage.tsx
Labels: 📬 API, ✨ Feature

#63 #9 [feat] contextMenu 모듈화
  src/components/Modal/AddCategory.tsx
  src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx
  src/components/Modal/MemoCollection/MemoCollection.tsx
  src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.tsx
  src/components/Modal/Search/Search.tsx
  src/components/SideBar/SideMessage/ContextMenu/ContextMenu.tsx
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/controllers/api.ts
  src/hooks/useContextMenu.tsx
  src/layout/Header/Header.tsx
  src/layout/SideBar/SideBar.tsx
  src/pages/Home/page.tsx
  src/pages/Memo/page.tsx
  src/stores/config/configStore.ts
  src/stores/modules/category.ts
  src/stores/modules/contextMenuSlice.ts
  src/stores/modules/counterSlice.ts
  src/stores/modules/memo.ts
  src/stores/modules/todoSlice.ts
Labels: ✨ Feature

#64 #11 [feat] contextMenu 전역 컴포넌트 설정
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/layout/MainLayout/MainLayout.tsx
Labels: ✨ Feature

#65 #11 [feat] useContextMenu 구현
  src/components/ContextMenu/ContextMenu.Style.ts
  src/components/SideBar/SideMessage/ContextMenu/ContextMenu.tsx
  src/components/SideBar/SideMessage/SideMessage.tsx
  src/hooks/useContextMenu.tsx
  src/layout/MainLayout/MainLayout.tsx
  src/stores/config/configStore.ts
  src/stores/modules/contextMenuSlice.ts
Labels: ✨ Feature

#67 #9 [feat] 컨텍스트메뉴 위치 조정
  src/hooks/useContextMenu.tsx
Labels: ✨ Feature
