Repository Team-useMemo/Jugger-Frontend-Web, pull requests merged in 2025-05, with the labels that each got.

#78 [feat] 테스트용 커밋
  src/components/Modal/AddCategory.tsx
  src/layout/Header/Header.tsx
  src/layout/SideBar/SideBar.tsx
  src/router/Root.tsx
  src/stores/modules/category.ts
  src/stores/modules/customBaseQuery.ts
Labels: ✨ Feature, ✅ Test

#89 #77 [remove] 불필요한 asset 제거
  src/assets/landing/CategoryModal1.png
  src/assets/landing/CategoryModal2.png
  src/assets/landing/CategoryModal3.png
  src/assets/landing/Chat.png
  src/assets/landing/ChatMobile.png
  src/assets/landing/ChatWeb.png
  src/assets/landing/CheckCategoryMobile.png
  src/assets/landing/CheckCategorypng.png
  src/assets/landing/DeviceMacbookAir.png
  src/assets/landing/Graphic.png
  src/assets/landing/MobileModal1.png
  src/assets/landing/MobileModal2.png
  src/assets/landing/Modal1.png
  src/assets/landing/modal2.png
  src/assets/landing/pigTail.svg
  src/assets/landing/upRight.svg
Labels: 📃 Docs

#90 Feat/#77 landing page
  package.json
  src/components/Index/Footer/Footer.tsx
  src/pages/Index/IndexPage.Style.ts
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🌏 Deploy, ✅ Test

#93 #77 [fix] 인덱스, 푸터 로고 수정
  src/assets/landing/FooterLogo.png
  src/components/Index/Footer/Footer.tsx
  src/components/Index/Section/Third/ThirdSection.Style.ts
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🎨 Styling

#94 #54 [Feat] 로컬 서버 연결
  .env
  .env.production
  src/components/Popup/Auth/Info/Info.tsx
  src/components/Popup/Auth/Term/Term.tsx
  src/pages/Login/page.tsx
  src/pages/Oauth/KakaoCallback.tsx
  src/pages/Root/page.tsx
  src/router/Root.tsx
  src/router/index.tsx
Labels: 📬 API, ✨ Feature
